#
# Copyright (c) 2023, TRE-FX Consortium Members
# Copyright (c) 2023-2024, Arjuna Technologies Limited, Newcastle upon Tyne, Tyne and Wear, UK.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  labels:
    app: config
data:
  lab_amqpbroker_host:         "192.168.1.213"
  lab_amqpbroker_port:         "5772"
  dmz_amqpbroker_host:         "192.168.1.213"
  dmz_amqpbroker_port:         "5872"
  sde_amqpbroker_host:         "192.168.1.213"
  sde_amqpbroker_port:         "5972"
  analysis_ds_amqpbroker_host: "192.168.1.213"
  analysis_ds_amqpbroker_port: "6072"
